/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import {Group} from 'three'
import React, {Ref} from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
    nodes: {
        Cube001: THREE.Mesh
        Cube001_1: THREE.Mesh
    }
    materials: {
        Plastic: THREE.MeshStandardMaterial
        Screen: THREE.MeshStandardMaterial
    }
}

const location = './meshes/phone-basic.glb';

export function PhoneBasic(props: JSX.IntrinsicElements['group'] & { innerRef: Ref<Group | undefined>}) {
    const {nodes, materials} = useGLTF(location) as GLTFResult;

    return (
        <group ref={props.innerRef} {...props} dispose={null}>
            <group scale={[0.02, 0.08, 0.004]}>
                <mesh geometry={nodes.Cube001.geometry} material={materials.Plastic}/>
                <mesh geometry={nodes.Cube001_1.geometry} material={materials.Screen}/>
            </group>
        </group>
    )
}

useGLTF.preload(location);